version: '3'

services:
  dbpostgresql:
    container_name: postgres
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      restart: unless-stopped
  pgadmin:
      container_name: pgadmin
      image: dpage/pgadmin4
      restart: always
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@admin.com
        PGADMIN_DEFAULT_PASSWORD: admin
      ports:
        - "5050:80"
  app:
    build: ../../Progetto/taass
    image: spring-boot-angular-1.0
    container_name: e-sommo-backend
    ports:
      - "8080:8080"
    depends_on:
      - dbpostgresql
  web:
    build:
      context: .
      dockerfile: src/main/js/ecommerce/Dockerfile.dev
    container_name: e-sommo-frontend
    ports:
      - "4200:4200"
    volumes:
      - /app/node_modules


